apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homelab-docs
  namespace: homelab-docs
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: &host homelab.khuedoan.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: homelab-docs
                port:
                  name: http
  tls:
    - secretName: homelab-docs-tls-certificate
      hosts:
        - *host
